# Generated by Django 3.0.7 on 2020-06-22 21:17

from django.db import migrations, models
import shop_basket.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='title',
            field=models.CharField(max_length=250, validators=[shop_basket.models.validate_title], verbose_name='order title'),
        ),
    ]
